# Generated by Django 5.1.15 on 2026-07-12 05:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_tag', models.TextField(blank=True, default='')),
                ('name', models.TextField()),
                ('serial_number', models.TextField(blank=True, null=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('acquisition_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DAMAGED', 'Damaged')], default='GOOD', max_length=16)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ALLOCATED', 'Allocated'), ('RESERVED', 'Reserved'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('LOST', 'Lost'), ('RETIRED', 'Retired'), ('DISPOSED', 'Disposed')], default='AVAILABLE', max_length=20)),
                ('location', models.TextField(blank=True, null=True)),
                ('is_bookable', models.BooleanField(default=False)),
                ('custom_fields', models.JSONField(default=dict)),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='organization.assetcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to='accounts.employee')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='organization.department')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='organization.organization')),
            ],
            options={
                'db_table': 'assets',
            },
        ),
        migrations.CreateModel(
            name='AssetDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.TextField()),
                ('label', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='assets.asset')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee')),
            ],
            options={
                'db_table': 'asset_documents',
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['org', 'status'], name='idx_assets_status'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['org', 'category'], name='idx_assets_category'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['org', 'department'], name='idx_assets_dept'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('org', 'asset_tag'), name='asset_tag_unique'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('org', 'serial_number'), name='asset_serial_unique'),
        ),
    ]
