# Generated by Django 5.1.15 on 2026-07-12 05:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth_uid', models.UUIDField(blank=True, null=True, unique=True)),
                ('full_name', models.TextField()),
                ('email', models.CharField(max_length=320)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('ASSET_MANAGER', 'Asset Manager'), ('DEPT_HEAD', 'Dept Head'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=16)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
