# Generated by Django 5.1.15 on 2026-07-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='access_status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING_APPROVAL', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='requested_role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('ASSET_MANAGER', 'Asset Manager'), ('DEPT_HEAD', 'Dept Head'), ('EMPLOYEE', 'Employee')], max_length=16, null=True),
        ),
    ]
