# Generated by Django 5.1.15 on 2026-07-12 05:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ASSET_ASSIGNED', 'Asset Assigned'), ('ASSET_RETURNED', 'Asset Returned'), ('TRANSFER_REQUESTED', 'Transfer Requested'), ('TRANSFER_APPROVED', 'Transfer Approved'), ('TRANSFER_REJECTED', 'Transfer Rejected'), ('MAINT_APPROVED', 'Maint Approved'), ('MAINT_REJECTED', 'Maint Rejected'), ('MAINT_RESOLVED', 'Maint Resolved'), ('BOOKING_CONFIRMED', 'Booking Confirmed'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('BOOKING_REMINDER', 'Booking Reminder'), ('OVERDUE_RETURN', 'Overdue Return'), ('AUDIT_ASSIGNED', 'Audit Assigned'), ('AUDIT_DISCREPANCY', 'Audit Discrepancy'), ('ROLE_CHANGED', 'Role Changed')], max_length=32)),
                ('title', models.TextField()),
                ('body', models.TextField(blank=True, null=True)),
                ('entity_type', models.TextField(blank=True, null=True)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.organization')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.employee')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.TextField()),
                ('entity_type', models.TextField()),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.organization')),
            ],
            options={
                'db_table': 'activity_logs',
                'indexes': [models.Index(fields=['entity_type', 'entity_id', '-created_at'], name='idx_activity_entity')],
            },
        ),
    ]
