# Generated by Django 5.1.15 on 2026-07-12 09:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employee_access_status_employee_requested_role'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=16),
        ),
        migrations.CreateModel(
            name='RoleJoinCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ASSET_MANAGER', 'Asset Manager'), ('DEPT_HEAD', 'Dept Head'), ('EMPLOYEE', 'Employee')], max_length=16)),
                ('code_hash', models.TextField(unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_rotated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_join_codes', to='organization.organization')),
            ],
            options={
                'db_table': 'role_join_codes',
            },
        ),
        migrations.CreateModel(
            name='SignupRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signup_ticket_hash', models.TextField(unique=True)),
                ('full_name', models.TextField()),
                ('email', models.CharField(max_length=320)),
                ('requested_role', models.CharField(max_length=16)),
                ('status', models.CharField(default='PENDING_EMAIL_VERIFICATION', max_length=32)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signup_decisions', to='accounts.employee')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signup_requests', to='accounts.employee')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signup_requests', to='organization.organization')),
                ('role_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.rolejoincode')),
            ],
            options={
                'db_table': 'signup_requests',
            },
        ),
        migrations.AddIndex(
            model_name='rolejoincode',
            index=models.Index(fields=['role', 'status'], name='idx_role_join_codes_lookup'),
        ),
        migrations.AddIndex(
            model_name='signuprequest',
            index=models.Index(fields=['org', 'status', '-created_at'], name='idx_signup_req_org_status'),
        ),
    ]
