# Generated by Django 5.1.15 on 2026-07-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_onboarding_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolejoincode',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
