# Generated by Django 5.1.15 on 2026-07-12 05:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('assets', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('scope_location', models.TextField(blank=True, null=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], default='DRAFT', max_length=16)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_cycles_closed', to='accounts.employee')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_cycles_created', to='accounts.employee')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.organization')),
                ('scope_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.department')),
            ],
            options={
                'db_table': 'audit_cycles',
            },
        ),
        migrations.CreateModel(
            name='AuditAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_assignments', to='accounts.employee')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='audits.auditcycle')),
            ],
            options={
                'db_table': 'audit_assignments',
                'constraints': [models.UniqueConstraint(fields=('cycle', 'auditor'), name='audit_assignment_pk')],
            },
        ),
        migrations.CreateModel(
            name='AuditItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('MISSING', 'Missing'), ('DAMAGED', 'Damaged')], default='PENDING', max_length=16)),
                ('notes', models.TextField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_items', to='assets.asset')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='audits.auditcycle')),
            ],
            options={
                'db_table': 'audit_items',
                'constraints': [models.UniqueConstraint(fields=('cycle', 'asset'), name='audit_item_unique')],
            },
        ),
    ]
